import dotenv from 'dotenv';
dotenv.config();

const v = process.env;
export const env = {
   APP_NAME: v.APP_NAME,
   AUTHOR: v.AUTHOR,
   EMAIL: v.EMAIL,
   HP: v.HP,
   NODE_ENV: v.NODE_ENV,
   PORT: v.PORT,
   APP_URL: v.APP_URL,
   APP_CLIENT_URL: v.APP_CLIENT_URL,

   DB_URL: v.DB_URL,
   DB_NAME: v.DB_NAME,
   DB_USERNAME: v.DB_USERNAME,
   DB_PASSWORD: v.DB_PASSWORD,
   DB_HOST: v.DB_HOST,
   DB_DIALECT: v.DB_DIALECT,
   DB_PORT: v.DB_PORT,

   ACCESS_TOKEN_SECRET: v.ACCESS_TOKEN_SECRET,
   REFRESH_TOKEN_SECRET: v.REFRESH_TOKEN_SECRET,
   ACCESS_TOKEN_EXPIRED: v.ACCESS_TOKEN_EXPIRED,
   REFRESH_TOKEN_EXPIRED: v.REFRESH_TOKEN_EXPIRED,

   TIMEOUT: v.TIMEOUT,
}